logging:
    file:
        name: logs/sboard.log
    level:
        jdbc:
            connection: info
            resultsettable: info
            sqlonly: info
            sqltiming: info
        root: info

mybatis:
    mapper-locations: classpath:mappers/**/*.xml

server:
    port: 8080
    servlet:
        context-path: /sboard

spring:
    application:
        name: sboard

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Lucky8909!
        url: jdbc:mysql://127.0.0.1:3306/jboard
        username: rhdyeji12
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: false

    mail:
        host: smtp.gmail.com
        port: 587
        username: rhdyeji12@gmail.com
        password: koby ukhm nkqq qvtv
        properties:
          mail:
              smtp:
                  auth: true
                  timeout: 5000
                  starttls:
                      enable: true

    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true

    servlet:
      multipart:
          location: uploads/
          max-file-size: 10MB

    thymeleaf:
        prefix: classpath:/templates

file:
    upload:
        path: uploads/
